<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        /**
         * 用finally块覆盖返回值也适用于在catch块内抛出或重新抛出的异常
         */
        function f() {
            try {
                throw 'bogus';
            } catch (e) {
                console.log('caught inner "bogud"');
                throw e;
            } finally {
                return false;
            }
        }

        try {
            f();
        } catch (e) {
            console.log('caught outer "bogus"');
        }
        /**
         * 打印结果：20行 caught inner "bogud"
        */
    </script>
</body>

</html>